DATA_PATH = "data"

METOSAT_API_ENDPOINT = "https://api.eumetsat.int"
METOSAT_DOWNLOAD_ENDPOINT = f"{METOSAT_API_ENDPOINT}/data/download"
METOSAT_BROWSE_ENDPOINT = f"{METOSAT_API_ENDPOINT}/data/browse"

METOSAT_CONSUMER_KEY = "W4UfXCVUrkqcio3PWn7dWputpcwa"
METOSAT_CONSUMER_SECRET = "MJZE2lAYnvDiaSUaKH3d13Ac1Jsa"
