DATA_PATH = "data"

METEOSAT_API_ENDPOINT = "https://api.eumetsat.int"
METEOSAT_DOWNLOAD_ENDPOINT = f"{METEOSAT_API_ENDPOINT}/data/download"
METEOSAT_BROWSE_ENDPOINT = f"{METEOSAT_API_ENDPOINT}/data/browse"

METEOSAT_CONSUMER_KEY = "W4UfXCVUrkqcio3PWn7dWputpcwa"
METEOSAT_CONSUMER_SECRET = "MJZE2lAYnvDiaSUaKH3d13Ac1Jsa"
